spring:
  application:
    name: zuul-server
server:
  port: 38089
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka1qaz@localhost:8761/eureka,http://eureka:eureka1qaz@localhost:8762/eureka

