jwt:
  password: dfajegfenfjdnbafdjiaonenafgdadfkebvnke923384325n9cdnenNIH*W)#ND((CJWENDF
  expire: 9600000
  issuer: com.wang
server:
  port: 38091
spring:
  application:
    name: authorize-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka1qaz@localhost:8761/eureka,http://eureka:eureka1qaz@localhost:8762/eureka