spring:
  application:
    name: eureka-server
server:
  port: 8762
security:
  basic:
    enabled: true
  user:
    name: eureka
    password: eureka1qaz
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:eureka1qaz@localhost:8761/eureka
  server:
    enable-self-preservation: false
